version: '3'

services: 

########################################
# Setup Backend
########################################
    server: 
        build: 
            context: ./server
        expose: 
            - "8000"
        ports:
            - "8000:8000"
        volumes:
            - ./server:/usr/src/server
        command: yarn run dev

########################################
# Setup Client
########################################        
    client: 
        build: 
            context: ./client
        expose: 
            - "3000"
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/client
        tty: true
        depends_on:
            - server
        command: yarn start