version: '3.7'

services: 
########################################
# Setup Backend
########################################
    server: 
        container_name: co-sketch-server-dev
        volumes:
            - ../packages/server:/usr/src/co-sketch/packages/server
        command: yarn run dev

########################################
# Setup Client
########################################        
    client: 
        build: 
            context: ../
            target: client
        image: co-sketch/client
        container_name: co-sketch-client-dev
        expose: 
            - "3000"
        ports:
            - "3000:3000"
        volumes:
            - ../packages/client:/usr/src/co-sketch/packages/client
        tty: true
        command: yarn start