version: '3.7'

services: 
########################################
# Setup Backend
########################################
    server: 
        expose: 
            - "8000"
        ports:
            - "8000:8000"
        volumes:
            - ../packages/server:/co-sketch/packages/server
        command: yarn run dev

########################################
# Setup Client
########################################        
    client: 
        expose: 
            - "3000"
        ports:
            - "3000:3000"
        volumes:
            - ../packages/client:/co-sketch/packages/client
        tty: true
        command: yarn start