version: '3.7'

services: 
    
########################################
# Setup Backend
########################################
    server: 
        build: 
            context: ../
            target: server
        image: co-sketch/server
        expose: 
            - "8000"
        ports:
            - "8000:8000"
        container_name: co-sketch-server
        command: yarn start