version: '3.7'


services:

########################################
# Setup Backend
########################################
    server:
        build: 
            args: 
                - NODE_ENV=production

########################################
# Setup Nginx
########################################
    nginx: 
        build: 
            context: ../
            target: nginx
        image: co-sketch/nginx
        expose: 
            - "80"
        ports:
            - "80:80"
        container_name: co-sketch-nginx