version: '3.7'

services: 
    
########################################
# Setup Backend
########################################
    server: 
        build: 
            context: ../
            target: server
        image: co-sketch/server
        container_name: co-sketch-server

########################################
# Setup Client
########################################        
    client: 
        build: 
            context: ../
            target: client
        image: co-sketch/client
        container_name: co-sketch-client